name: tots_flutter_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0-119.0.dev <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.7
  go_router: ^12.1.1
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
